### your site title here

title: Amy's Website
baseurl:  # name of the repository
email: amy@amyrom.tech



highlighter: rouge
markdown: kramdown
### exclude the instructions / write-up in the README.md


# Tracker
analytics: 

# Comments
disqus-shortname: amy7296


#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []
  
kramdown:
  parse_block_html: true

sass:
 style: compressed

exclude:
- README.md


gems: [jekyll-seo-tag, jekyll-paginate, jekyll-toc]
